apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tc-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
    - name: dockerconfig-ws
  params:
    - name: build-image
      description: Image name to build
  tasks:
    - name: npminstall
      taskRef:
        name: npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: tests
      taskRef:
        name: jasmine
      runAfter:
        - npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      taskRef:
        kind: ClusterTask
        name: buildah
      runAfter:
        - tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
      params:
        - name: IMAGE
          value: "$(params.build-image)"
